parameters:
   contact_notification.notification.class: Contact\Bundle\NotificationBundle\Controller\NotificationController

services:
    contact.notify:
       class: %contact_notification.notification.class%
       arguments:
            session: @session
    contact.twig.notification_extension:
        class: Contact\Bundle\NotificationBundle\Twig\NotificationExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
