contact_notification:
    resource: "@ContactNotificationBundle/Resources/config/routing.yml"
    prefix:   /

contact_contact:
    resource: "@ContactContactBundle/Resources/config/routing.yml"
    prefix:   /

