parameters:
#    contact_contact.example.class: Contact\Bundle\ContactBundle\Example

services:
#    contact_contact.example:
#        class: %contact_contact.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

# services:
#    contact_contact.manager.contact:
#         class: Contact\Bundle\ContactBundle\Manager\ContactManager
#         arguments: [ @service_container, 'ContactContactBundle:Contact']