Contact\Bundle\ContactBundle\Entity\Contact:
    type: entity
    table: contact
    repositoryClass: Contact\Bundle\ContactBundle\Repository\Contact
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
        surname:
            type: string
            length: 255
        middleNames:
            type: string
            length: 255
            nullable: TRUE
        dateAdded:
            type: datetime
            nullable: TRUE
        favourite:
            type: boolean
    lifecycleCallbacks:
        prePersist: [setDateAddedToNow]
    oneToMany:
        addresses:
            targetEntity: ContactAddress
            mappedBy: contact