Contact\Bundle\ContactBundle\Entity\Contact:
    type: entity
    table: contact
    repositoryClass: Contact\Bundle\ContactBundle\Repository\Contact
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
        surname:
            type: string
            length: 255
        middleNames:
            type: string
            length: 255
        dateAdded:
            type: datetime
        favourite:
            type: boolean
    lifecycleCallbacks: {  }
